schema_version: 1

context:
  name: pygama
  version: "2.2.4"
  # pylegendmeta is Python 3.10 to get around a selector issue,
  # so use Python 3.10 even though source is 3.9+.
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pygama-${{ version }}.tar.gz
  sha256: ec7be2f7ffd6b1ba450aa45d0f8d5b935785a60bf1653d63e959389960a9858d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pygama = pygama.cli:pygama_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.2
    - setuptools-scm >=7
  run:
    - python >=${{ python_min }}
    - hist
    - colorlog
    - dbetto
    - dspeed >=1.7
    - h5py >=3.2
    - iminuit
    - legend-pydataobj >=1.14
    - pylegendmeta >=0.9
    - matplotlib-base
    - numba !=0.53.*,!=0.54.*,!=0.57
    - numpy >=1.21
    - pandas >=1.4.4
    - pytables
    - pint
    - pyyaml
    - scikit-learn
    - scipy >=1.0.1
    - tqdm >=4.66

tests:
  - python:
      imports:
        - pygama
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - conda list
      - pygama --help

about:
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Python package for data processing and analysis
  description: |
    pygama is a Python package for:

    * converting physics data acquisition system output to LH5-format
      HDF5 files (functionality provided by the legend-pydataobj and
      legend-daq2lh5 packages)
    * performing bulk digital signal processing (DSP) on time-series data
      (functionality provided by the dspeed package)
    * optimizing DSP routines and tuning associated analysis parameters
    * generating and selecting high-level event data for further analysis
  homepage: https://github.com/legend-exp/pygama
  repository: https://github.com/legend-exp/pygama
  documentation: https://pygama.readthedocs.io/

extra:
  recipe-maintainers:
    - gipert
    - matthewfeickert
